<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math/vector3.proto

namespace GPBMetadata\Math;

class Vector3
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a88010a126d6174682f766563746f72332e70726f746f12046d617468222a0a07566563746f723312090a017818012001280112090a017918022001280112090a017a18032001280142385a366769746875622e636f6d2f434344506c616e65742f636364706c616e65742d6261636b656e642f706b672f6170692f76312f6d617468620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

