<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: licenses/licenses.proto

namespace Licenses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>licenses.FindByOwnerIDResp</code>
 */
class FindByOwnerIDResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .licenses.License licenses = 1;</code>
     */
    private $licenses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Licenses\License[]|\Google\Protobuf\Internal\RepeatedField $licenses
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Licenses\Licenses::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .licenses.License licenses = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLicenses()
    {
        return $this->licenses;
    }

    /**
     * Generated from protobuf field <code>repeated .licenses.License licenses = 1;</code>
     * @param \Licenses\License[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLicenses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Licenses\License::class);
        $this->licenses = $arr;

        return $this;
    }

}

