<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: licenses/licenses.proto

namespace Licenses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>licenses.License</code>
 */
class License extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 owner_id = 1;</code>
     */
    protected $owner_id = 0;
    /**
     * Generated from protobuf field <code>int32 created_at = 2;</code>
     */
    protected $created_at = 0;
    /**
     * Generated from protobuf field <code>string license_type = 3;</code>
     */
    protected $license_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $owner_id
     *     @type int $created_at
     *     @type string $license_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Licenses\Licenses::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 owner_id = 1;</code>
     * @return int
     */
    public function getOwnerId()
    {
        return $this->owner_id;
    }

    /**
     * Generated from protobuf field <code>int32 owner_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 created_at = 2;</code>
     * @return int
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>int32 created_at = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string license_type = 3;</code>
     * @return string
     */
    public function getLicenseType()
    {
        return $this->license_type;
    }

    /**
     * Generated from protobuf field <code>string license_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLicenseType($var)
    {
        GPBUtil::checkString($var, True);
        $this->license_type = $var;

        return $this;
    }

}

