<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: characterstats/characterstats.proto

namespace Characterstats;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>characterstats.GetReq</code>
 */
class GetReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 character_id = 1;</code>
     */
    protected $character_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $character_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Characterstats\Characterstats::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 character_id = 1;</code>
     * @return int
     */
    public function getCharacterId()
    {
        return $this->character_id;
    }

    /**
     * Generated from protobuf field <code>int32 character_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCharacterId($var)
    {
        GPBUtil::checkInt32($var);
        $this->character_id = $var;

        return $this;
    }

}

