<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: characterstats/characterstats.proto

namespace Characterstats;

use UnexpectedValueException;

/**
 * Protobuf type <code>characterstats.Job</code>
 */
class Job
{
    /**
     * Generated from protobuf enum <code>FARMER = 0;</code>
     */
    const FARMER = 0;
    /**
     * Generated from protobuf enum <code>TOWTRUCK = 1;</code>
     */
    const TOWTRUCK = 1;
    /**
     * Generated from protobuf enum <code>TRUCKER = 2;</code>
     */
    const TRUCKER = 2;

    private static $valueToName = [
        self::FARMER => 'FARMER',
        self::TOWTRUCK => 'TOWTRUCK',
        self::TRUCKER => 'TRUCKER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

