<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: characterstats/characterstats.proto

namespace Characterstats;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>characterstats.JobStats</code>
 */
class JobStats extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 time_played = 1;</code>
     */
    protected $time_played = 0;
    /**
     * Generated from protobuf field <code>int64 times_completed = 2;</code>
     */
    protected $times_completed = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $time_played
     *     @type int|string $times_completed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Characterstats\Characterstats::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 time_played = 1;</code>
     * @return int|string
     */
    public function getTimePlayed()
    {
        return $this->time_played;
    }

    /**
     * Generated from protobuf field <code>int64 time_played = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimePlayed($var)
    {
        GPBUtil::checkInt64($var);
        $this->time_played = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 times_completed = 2;</code>
     * @return int|string
     */
    public function getTimesCompleted()
    {
        return $this->times_completed;
    }

    /**
     * Generated from protobuf field <code>int64 times_completed = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimesCompleted($var)
    {
        GPBUtil::checkInt64($var);
        $this->times_completed = $var;

        return $this;
    }

}

