<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: characterstats/characterstats.proto

namespace Characterstats;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>characterstats.Stats</code>
 */
class Stats extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 time_played = 1;</code>
     */
    protected $time_played = 0;
    /**
     * Generated from protobuf field <code>int64 sessions_count = 2;</code>
     */
    protected $sessions_count = 0;
    /**
     * Generated from protobuf field <code>int64 distance_traveled_foot = 3;</code>
     */
    protected $distance_traveled_foot = 0;
    /**
     * Generated from protobuf field <code>int64 distance_traveled_vehicle = 4;</code>
     */
    protected $distance_traveled_vehicle = 0;
    /**
     * Generated from protobuf field <code>.characterstats.JobStats job_farmer_stats = 5;</code>
     */
    protected $job_farmer_stats = null;
    /**
     * Generated from protobuf field <code>.characterstats.JobStats job_towtruck_stats = 6;</code>
     */
    protected $job_towtruck_stats = null;
    /**
     * Generated from protobuf field <code>.characterstats.JobStats job_trucker_stats = 7;</code>
     */
    protected $job_trucker_stats = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $time_played
     *     @type int|string $sessions_count
     *     @type int|string $distance_traveled_foot
     *     @type int|string $distance_traveled_vehicle
     *     @type \Characterstats\JobStats $job_farmer_stats
     *     @type \Characterstats\JobStats $job_towtruck_stats
     *     @type \Characterstats\JobStats $job_trucker_stats
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Characterstats\Characterstats::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 time_played = 1;</code>
     * @return int|string
     */
    public function getTimePlayed()
    {
        return $this->time_played;
    }

    /**
     * Generated from protobuf field <code>int64 time_played = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimePlayed($var)
    {
        GPBUtil::checkInt64($var);
        $this->time_played = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 sessions_count = 2;</code>
     * @return int|string
     */
    public function getSessionsCount()
    {
        return $this->sessions_count;
    }

    /**
     * Generated from protobuf field <code>int64 sessions_count = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSessionsCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->sessions_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 distance_traveled_foot = 3;</code>
     * @return int|string
     */
    public function getDistanceTraveledFoot()
    {
        return $this->distance_traveled_foot;
    }

    /**
     * Generated from protobuf field <code>int64 distance_traveled_foot = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDistanceTraveledFoot($var)
    {
        GPBUtil::checkInt64($var);
        $this->distance_traveled_foot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 distance_traveled_vehicle = 4;</code>
     * @return int|string
     */
    public function getDistanceTraveledVehicle()
    {
        return $this->distance_traveled_vehicle;
    }

    /**
     * Generated from protobuf field <code>int64 distance_traveled_vehicle = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDistanceTraveledVehicle($var)
    {
        GPBUtil::checkInt64($var);
        $this->distance_traveled_vehicle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.characterstats.JobStats job_farmer_stats = 5;</code>
     * @return \Characterstats\JobStats
     */
    public function getJobFarmerStats()
    {
        return $this->job_farmer_stats;
    }

    /**
     * Generated from protobuf field <code>.characterstats.JobStats job_farmer_stats = 5;</code>
     * @param \Characterstats\JobStats $var
     * @return $this
     */
    public function setJobFarmerStats($var)
    {
        GPBUtil::checkMessage($var, \Characterstats\JobStats::class);
        $this->job_farmer_stats = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.characterstats.JobStats job_towtruck_stats = 6;</code>
     * @return \Characterstats\JobStats
     */
    public function getJobTowtruckStats()
    {
        return $this->job_towtruck_stats;
    }

    /**
     * Generated from protobuf field <code>.characterstats.JobStats job_towtruck_stats = 6;</code>
     * @param \Characterstats\JobStats $var
     * @return $this
     */
    public function setJobTowtruckStats($var)
    {
        GPBUtil::checkMessage($var, \Characterstats\JobStats::class);
        $this->job_towtruck_stats = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.characterstats.JobStats job_trucker_stats = 7;</code>
     * @return \Characterstats\JobStats
     */
    public function getJobTruckerStats()
    {
        return $this->job_trucker_stats;
    }

    /**
     * Generated from protobuf field <code>.characterstats.JobStats job_trucker_stats = 7;</code>
     * @param \Characterstats\JobStats $var
     * @return $this
     */
    public function setJobTruckerStats($var)
    {
        GPBUtil::checkMessage($var, \Characterstats\JobStats::class);
        $this->job_trucker_stats = $var;

        return $this;
    }

}

