<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: characters/characters.proto

namespace Characters;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>characters.Character</code>
 */
class Character extends \Google\Protobuf\Internal\Message
{
    /**
     * Character ID
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Character's owner account ID
     *
     * Generated from protobuf field <code>int32 owner_id = 2;</code>
     */
    protected $owner_id = 0;
    /**
     * Character creation UNIX timestamp
     *
     * Generated from protobuf field <code>int32 created_at = 3;</code>
     */
    protected $created_at = 0;
    /**
     * Character last login UNIX timestamp
     *
     * Generated from protobuf field <code>int32 last_login_at = 4;</code>
     */
    protected $last_login_at = 0;
    /**
     * Character's person info
     *
     * Generated from protobuf field <code>.characters.PersonInfo person_info = 5;</code>
     */
    protected $person_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *           Character ID
     *     @type int $owner_id
     *           Character's owner account ID
     *     @type int $created_at
     *           Character creation UNIX timestamp
     *     @type int $last_login_at
     *           Character last login UNIX timestamp
     *     @type \Characters\PersonInfo $person_info
     *           Character's person info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Characters\Characters::initOnce();
        parent::__construct($data);
    }

    /**
     * Character ID
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Character ID
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Character's owner account ID
     *
     * Generated from protobuf field <code>int32 owner_id = 2;</code>
     * @return int
     */
    public function getOwnerId()
    {
        return $this->owner_id;
    }

    /**
     * Character's owner account ID
     *
     * Generated from protobuf field <code>int32 owner_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * Character creation UNIX timestamp
     *
     * Generated from protobuf field <code>int32 created_at = 3;</code>
     * @return int
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Character creation UNIX timestamp
     *
     * Generated from protobuf field <code>int32 created_at = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Character last login UNIX timestamp
     *
     * Generated from protobuf field <code>int32 last_login_at = 4;</code>
     * @return int
     */
    public function getLastLoginAt()
    {
        return $this->last_login_at;
    }

    /**
     * Character last login UNIX timestamp
     *
     * Generated from protobuf field <code>int32 last_login_at = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLastLoginAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->last_login_at = $var;

        return $this;
    }

    /**
     * Character's person info
     *
     * Generated from protobuf field <code>.characters.PersonInfo person_info = 5;</code>
     * @return \Characters\PersonInfo
     */
    public function getPersonInfo()
    {
        return $this->person_info;
    }

    /**
     * Character's person info
     *
     * Generated from protobuf field <code>.characters.PersonInfo person_info = 5;</code>
     * @param \Characters\PersonInfo $var
     * @return $this
     */
    public function setPersonInfo($var)
    {
        GPBUtil::checkMessage($var, \Characters\PersonInfo::class);
        $this->person_info = $var;

        return $this;
    }

}

