<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: characters/characters.proto

namespace Characters;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>characters.CharacterAppearance</code>
 */
class CharacterAppearance extends \Google\Protobuf\Internal\Message
{
    /**
     * Character appearance data JSON
     *
     * Generated from protobuf field <code>string appearance_json = 1;</code>
     */
    protected $appearance_json = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $appearance_json
     *           Character appearance data JSON
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Characters\Characters::initOnce();
        parent::__construct($data);
    }

    /**
     * Character appearance data JSON
     *
     * Generated from protobuf field <code>string appearance_json = 1;</code>
     * @return string
     */
    public function getAppearanceJson()
    {
        return $this->appearance_json;
    }

    /**
     * Character appearance data JSON
     *
     * Generated from protobuf field <code>string appearance_json = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppearanceJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->appearance_json = $var;

        return $this;
    }

}

