<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: characters/characters.proto

namespace Characters;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>characters.CharacterClothes</code>
 */
class CharacterClothes extends \Google\Protobuf\Internal\Message
{
    /**
     * Character clothes JSON
     *
     * Generated from protobuf field <code>string clothes_json = 1;</code>
     */
    protected $clothes_json = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $clothes_json
     *           Character clothes JSON
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Characters\Characters::initOnce();
        parent::__construct($data);
    }

    /**
     * Character clothes JSON
     *
     * Generated from protobuf field <code>string clothes_json = 1;</code>
     * @return string
     */
    public function getClothesJson()
    {
        return $this->clothes_json;
    }

    /**
     * Character clothes JSON
     *
     * Generated from protobuf field <code>string clothes_json = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setClothesJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->clothes_json = $var;

        return $this;
    }

}

