<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: characters/characters.proto

namespace Characters;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Create method request parameter
 *
 * Generated from protobuf message <code>characters.CreateRequest</code>
 */
class CreateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 owner_id = 1;</code>
     */
    protected $owner_id = 0;
    /**
     * Character's person info
     *
     * Generated from protobuf field <code>.characters.PersonInfo person_info = 2;</code>
     */
    protected $person_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $owner_id
     *     @type \Characters\PersonInfo $person_info
     *           Character's person info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Characters\Characters::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 owner_id = 1;</code>
     * @return int
     */
    public function getOwnerId()
    {
        return $this->owner_id;
    }

    /**
     * Generated from protobuf field <code>int32 owner_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * Character's person info
     *
     * Generated from protobuf field <code>.characters.PersonInfo person_info = 2;</code>
     * @return \Characters\PersonInfo
     */
    public function getPersonInfo()
    {
        return $this->person_info;
    }

    /**
     * Character's person info
     *
     * Generated from protobuf field <code>.characters.PersonInfo person_info = 2;</code>
     * @param \Characters\PersonInfo $var
     * @return $this
     */
    public function setPersonInfo($var)
    {
        GPBUtil::checkMessage($var, \Characters\PersonInfo::class);
        $this->person_info = $var;

        return $this;
    }

}

