<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: characters/characters.proto

namespace Characters;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * FindByOwnerID method response message
 *
 * Generated from protobuf message <code>characters.FindByOwnerIDResponse</code>
 */
class FindByOwnerIDResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Characters found by this method
     *
     * Generated from protobuf field <code>repeated .characters.Character characters = 1;</code>
     */
    private $characters;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Characters\Character[]|\Google\Protobuf\Internal\RepeatedField $characters
     *           Characters found by this method
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Characters\Characters::initOnce();
        parent::__construct($data);
    }

    /**
     * Characters found by this method
     *
     * Generated from protobuf field <code>repeated .characters.Character characters = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCharacters()
    {
        return $this->characters;
    }

    /**
     * Characters found by this method
     *
     * Generated from protobuf field <code>repeated .characters.Character characters = 1;</code>
     * @param \Characters\Character[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCharacters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Characters\Character::class);
        $this->characters = $arr;

        return $this;
    }

}

