<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: characters/characters.proto

namespace Characters;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Character's person info
 *
 * Generated from protobuf message <code>characters.PersonInfo</code>
 */
class PersonInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * First name of the character
     *
     * Generated from protobuf field <code>string first_name = 1;</code>
     */
    protected $first_name = '';
    /**
     * Last name of the character
     *
     * Generated from protobuf field <code>string last_name = 2;</code>
     */
    protected $last_name = '';
    /**
     * Character's bio text
     *
     * Generated from protobuf field <code>string bio = 3;</code>
     */
    protected $bio = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $first_name
     *           First name of the character
     *     @type string $last_name
     *           Last name of the character
     *     @type string $bio
     *           Character's bio text
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Characters\Characters::initOnce();
        parent::__construct($data);
    }

    /**
     * First name of the character
     *
     * Generated from protobuf field <code>string first_name = 1;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * First name of the character
     *
     * Generated from protobuf field <code>string first_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_name = $var;

        return $this;
    }

    /**
     * Last name of the character
     *
     * Generated from protobuf field <code>string last_name = 2;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * Last name of the character
     *
     * Generated from protobuf field <code>string last_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_name = $var;

        return $this;
    }

    /**
     * Character's bio text
     *
     * Generated from protobuf field <code>string bio = 3;</code>
     * @return string
     */
    public function getBio()
    {
        return $this->bio;
    }

    /**
     * Character's bio text
     *
     * Generated from protobuf field <code>string bio = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBio($var)
    {
        GPBUtil::checkString($var, True);
        $this->bio = $var;

        return $this;
    }

}

