<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: characters/characters.proto

namespace Characters;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SetSpawnLocation method request parameter
 *
 * Generated from protobuf message <code>characters.SetSpawnLocationRequest</code>
 */
class SetSpawnLocationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Character ID
     *
     * Generated from protobuf field <code>int32 character_id = 1;</code>
     */
    protected $character_id = 0;
    /**
     * Character's new spawn location
     *
     * Generated from protobuf field <code>.characters.SpawnLocation spawn_location = 2;</code>
     */
    protected $spawn_location = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $character_id
     *           Character ID
     *     @type \Characters\SpawnLocation $spawn_location
     *           Character's new spawn location
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Characters\Characters::initOnce();
        parent::__construct($data);
    }

    /**
     * Character ID
     *
     * Generated from protobuf field <code>int32 character_id = 1;</code>
     * @return int
     */
    public function getCharacterId()
    {
        return $this->character_id;
    }

    /**
     * Character ID
     *
     * Generated from protobuf field <code>int32 character_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCharacterId($var)
    {
        GPBUtil::checkInt32($var);
        $this->character_id = $var;

        return $this;
    }

    /**
     * Character's new spawn location
     *
     * Generated from protobuf field <code>.characters.SpawnLocation spawn_location = 2;</code>
     * @return \Characters\SpawnLocation
     */
    public function getSpawnLocation()
    {
        return $this->spawn_location;
    }

    /**
     * Character's new spawn location
     *
     * Generated from protobuf field <code>.characters.SpawnLocation spawn_location = 2;</code>
     * @param \Characters\SpawnLocation $var
     * @return $this
     */
    public function setSpawnLocation($var)
    {
        GPBUtil::checkMessage($var, \Characters\SpawnLocation::class);
        $this->spawn_location = $var;

        return $this;
    }

}

