<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicles/vehicles.proto

namespace Vehicles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vehicles.BodyColor</code>
 */
class BodyColor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 r = 1;</code>
     */
    protected $r = 0;
    /**
     * Generated from protobuf field <code>int32 g = 2;</code>
     */
    protected $g = 0;
    /**
     * Generated from protobuf field <code>int32 b = 3;</code>
     */
    protected $b = 0;
    /**
     * Generated from protobuf field <code>int32 paint = 4;</code>
     */
    protected $paint = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $r
     *     @type int $g
     *     @type int $b
     *     @type int $paint
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vehicles\Vehicles::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 r = 1;</code>
     * @return int
     */
    public function getR()
    {
        return $this->r;
    }

    /**
     * Generated from protobuf field <code>int32 r = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setR($var)
    {
        GPBUtil::checkInt32($var);
        $this->r = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 g = 2;</code>
     * @return int
     */
    public function getG()
    {
        return $this->g;
    }

    /**
     * Generated from protobuf field <code>int32 g = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setG($var)
    {
        GPBUtil::checkInt32($var);
        $this->g = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 b = 3;</code>
     * @return int
     */
    public function getB()
    {
        return $this->b;
    }

    /**
     * Generated from protobuf field <code>int32 b = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setB($var)
    {
        GPBUtil::checkInt32($var);
        $this->b = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 paint = 4;</code>
     * @return int
     */
    public function getPaint()
    {
        return $this->paint;
    }

    /**
     * Generated from protobuf field <code>int32 paint = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPaint($var)
    {
        GPBUtil::checkInt32($var);
        $this->paint = $var;

        return $this;
    }

}

