<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicles/vehicles.proto

namespace Vehicles;

use UnexpectedValueException;

/**
 * Protobuf type <code>vehicles.EngineType</code>
 */
class EngineType
{
    /**
     * Generated from protobuf enum <code>TYPE_UNSPECIFIED = 0;</code>
     */
    const TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>TYPE_GASOLINE = 1;</code>
     */
    const TYPE_GASOLINE = 1;
    /**
     * Generated from protobuf enum <code>TYPE_DIESEL = 2;</code>
     */
    const TYPE_DIESEL = 2;
    /**
     * Generated from protobuf enum <code>TYPE_PROPANE = 3;</code>
     */
    const TYPE_PROPANE = 3;
    /**
     * Generated from protobuf enum <code>TYPE_CNG = 4;</code>
     */
    const TYPE_CNG = 4;
    /**
     * Generated from protobuf enum <code>TYPE_ETHANOL = 5;</code>
     */
    const TYPE_ETHANOL = 5;
    /**
     * Generated from protobuf enum <code>TYPE_BIO_DIESEL = 6;</code>
     */
    const TYPE_BIO_DIESEL = 6;
    /**
     * Generated from protobuf enum <code>TYPE_ELECTRIC = 7;</code>
     */
    const TYPE_ELECTRIC = 7;
    /**
     * Generated from protobuf enum <code>TYPE_HYBRID = 8;</code>
     */
    const TYPE_HYBRID = 8;
    /**
     * Generated from protobuf enum <code>TYPE_HYDROGEN = 9;</code>
     */
    const TYPE_HYDROGEN = 9;
    /**
     * Generated from protobuf enum <code>TYPE_KEROSENE = 10;</code>
     */
    const TYPE_KEROSENE = 10;

    private static $valueToName = [
        self::TYPE_UNSPECIFIED => 'TYPE_UNSPECIFIED',
        self::TYPE_GASOLINE => 'TYPE_GASOLINE',
        self::TYPE_DIESEL => 'TYPE_DIESEL',
        self::TYPE_PROPANE => 'TYPE_PROPANE',
        self::TYPE_CNG => 'TYPE_CNG',
        self::TYPE_ETHANOL => 'TYPE_ETHANOL',
        self::TYPE_BIO_DIESEL => 'TYPE_BIO_DIESEL',
        self::TYPE_ELECTRIC => 'TYPE_ELECTRIC',
        self::TYPE_HYBRID => 'TYPE_HYBRID',
        self::TYPE_HYDROGEN => 'TYPE_HYDROGEN',
        self::TYPE_KEROSENE => 'TYPE_KEROSENE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

