<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicles/vehicles.proto

namespace Vehicles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vehicles.GetCharacterVehiclesListReq</code>
 */
class GetCharacterVehiclesListReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 character_id = 1;</code>
     */
    protected $character_id = 0;
    /**
     * Generated from protobuf field <code>int32 offset = 2;</code>
     */
    protected $offset = 0;
    /**
     * Generated from protobuf field <code>int32 count = 3;</code>
     */
    protected $count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $character_id
     *     @type int $offset
     *     @type int $count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vehicles\Vehicles::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 character_id = 1;</code>
     * @return int
     */
    public function getCharacterId()
    {
        return $this->character_id;
    }

    /**
     * Generated from protobuf field <code>int32 character_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCharacterId($var)
    {
        GPBUtil::checkInt32($var);
        $this->character_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 offset = 2;</code>
     * @return int
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>int32 offset = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 count = 3;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int32 count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

}

