<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicles/vehicles.proto

namespace Vehicles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vehicles.GetDirtLevelResp</code>
 */
class GetDirtLevelResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float dirt_level = 1;</code>
     */
    protected $dirt_level = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $dirt_level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vehicles\Vehicles::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float dirt_level = 1;</code>
     * @return float
     */
    public function getDirtLevel()
    {
        return $this->dirt_level;
    }

    /**
     * Generated from protobuf field <code>float dirt_level = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setDirtLevel($var)
    {
        GPBUtil::checkFloat($var);
        $this->dirt_level = $var;

        return $this;
    }

}

