<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicles/vehicles.proto

namespace Vehicles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vehicles.GetHealthResp</code>
 */
class GetHealthResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 health = 1;</code>
     */
    protected $health = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $health
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vehicles\Vehicles::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 health = 1;</code>
     * @return int
     */
    public function getHealth()
    {
        return $this->health;
    }

    /**
     * Generated from protobuf field <code>int32 health = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setHealth($var)
    {
        GPBUtil::checkInt32($var);
        $this->health = $var;

        return $this;
    }

}

