<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicles/vehicles.proto

namespace Vehicles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vehicles.VehicleMod</code>
 */
class VehicleMod extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string mod_type = 1;</code>
     */
    protected $mod_type = '';
    /**
     * Generated from protobuf field <code>int32 mod_index = 2;</code>
     */
    protected $mod_index = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mod_type
     *     @type int $mod_index
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vehicles\Vehicles::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string mod_type = 1;</code>
     * @return string
     */
    public function getModType()
    {
        return $this->mod_type;
    }

    /**
     * Generated from protobuf field <code>string mod_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setModType($var)
    {
        GPBUtil::checkString($var, True);
        $this->mod_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 mod_index = 2;</code>
     * @return int
     */
    public function getModIndex()
    {
        return $this->mod_index;
    }

    /**
     * Generated from protobuf field <code>int32 mod_index = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setModIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->mod_index = $var;

        return $this;
    }

}

