<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicles/vehicles.proto

namespace Vehicles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vehicles.VehiclePassport</code>
 */
class VehiclePassport extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string model = 1;</code>
     */
    protected $model = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int32 model_year = 3;</code>
     */
    protected $model_year = 0;
    /**
     * Generated from protobuf field <code>int32 engine_power = 4;</code>
     */
    protected $engine_power = 0;
    /**
     * Generated from protobuf field <code>int32 engine_volume = 5;</code>
     */
    protected $engine_volume = 0;
    /**
     * Generated from protobuf field <code>.vehicles.EngineType engine_type = 6;</code>
     */
    protected $engine_type = 0;
    /**
     * Generated from protobuf field <code>.vehicles.EcoStandard eco_standard = 7;</code>
     */
    protected $eco_standard = 0;
    /**
     * Generated from protobuf field <code>int32 mass = 8;</code>
     */
    protected $mass = 0;
    /**
     * Generated from protobuf field <code>int32 inventory_slots = 9;</code>
     */
    protected $inventory_slots = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $model
     *     @type string $name
     *     @type int $model_year
     *     @type int $engine_power
     *     @type int $engine_volume
     *     @type int $engine_type
     *     @type int $eco_standard
     *     @type int $mass
     *     @type int $inventory_slots
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vehicles\Vehicles::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string model = 1;</code>
     * @return string
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Generated from protobuf field <code>string model = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 model_year = 3;</code>
     * @return int
     */
    public function getModelYear()
    {
        return $this->model_year;
    }

    /**
     * Generated from protobuf field <code>int32 model_year = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setModelYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->model_year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 engine_power = 4;</code>
     * @return int
     */
    public function getEnginePower()
    {
        return $this->engine_power;
    }

    /**
     * Generated from protobuf field <code>int32 engine_power = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setEnginePower($var)
    {
        GPBUtil::checkInt32($var);
        $this->engine_power = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 engine_volume = 5;</code>
     * @return int
     */
    public function getEngineVolume()
    {
        return $this->engine_volume;
    }

    /**
     * Generated from protobuf field <code>int32 engine_volume = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setEngineVolume($var)
    {
        GPBUtil::checkInt32($var);
        $this->engine_volume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.vehicles.EngineType engine_type = 6;</code>
     * @return int
     */
    public function getEngineType()
    {
        return $this->engine_type;
    }

    /**
     * Generated from protobuf field <code>.vehicles.EngineType engine_type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setEngineType($var)
    {
        GPBUtil::checkEnum($var, \Vehicles\EngineType::class);
        $this->engine_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.vehicles.EcoStandard eco_standard = 7;</code>
     * @return int
     */
    public function getEcoStandard()
    {
        return $this->eco_standard;
    }

    /**
     * Generated from protobuf field <code>.vehicles.EcoStandard eco_standard = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setEcoStandard($var)
    {
        GPBUtil::checkEnum($var, \Vehicles\EcoStandard::class);
        $this->eco_standard = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 mass = 8;</code>
     * @return int
     */
    public function getMass()
    {
        return $this->mass;
    }

    /**
     * Generated from protobuf field <code>int32 mass = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setMass($var)
    {
        GPBUtil::checkInt32($var);
        $this->mass = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 inventory_slots = 9;</code>
     * @return int
     */
    public function getInventorySlots()
    {
        return $this->inventory_slots;
    }

    /**
     * Generated from protobuf field <code>int32 inventory_slots = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setInventorySlots($var)
    {
        GPBUtil::checkInt32($var);
        $this->inventory_slots = $var;

        return $this;
    }

}

