<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicles/vehicles.proto

namespace Vehicles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Структура транспортного средства
 *
 * Generated from protobuf message <code>vehicles.Vehicle</code>
 */
class Vehicle extends \Google\Protobuf\Internal\Message
{
    /**
     * ID транспортного средства
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Персонаж, владеющий транспортным средством
     *
     * Generated from protobuf field <code>int32 owner_id = 2;</code>
     */
    protected $owner_id = 0;
    /**
     * Время создания
     *
     * Generated from protobuf field <code>int32 created_at = 3;</code>
     */
    protected $created_at = 0;
    /**
     * Модель
     *
     * Generated from protobuf field <code>string model = 4;</code>
     */
    protected $model = '';
    /**
     * Заблокирован ли спавн
     *
     * Generated from protobuf field <code>bool is_locked = 5;</code>
     */
    protected $is_locked = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *           ID транспортного средства
     *     @type int $owner_id
     *           Персонаж, владеющий транспортным средством
     *     @type int $created_at
     *           Время создания
     *     @type string $model
     *           Модель
     *     @type bool $is_locked
     *           Заблокирован ли спавн
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vehicles\Vehicles::initOnce();
        parent::__construct($data);
    }

    /**
     * ID транспортного средства
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * ID транспортного средства
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Персонаж, владеющий транспортным средством
     *
     * Generated from protobuf field <code>int32 owner_id = 2;</code>
     * @return int
     */
    public function getOwnerId()
    {
        return $this->owner_id;
    }

    /**
     * Персонаж, владеющий транспортным средством
     *
     * Generated from protobuf field <code>int32 owner_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * Время создания
     *
     * Generated from protobuf field <code>int32 created_at = 3;</code>
     * @return int
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Время создания
     *
     * Generated from protobuf field <code>int32 created_at = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Модель
     *
     * Generated from protobuf field <code>string model = 4;</code>
     * @return string
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Модель
     *
     * Generated from protobuf field <code>string model = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->model = $var;

        return $this;
    }

    /**
     * Заблокирован ли спавн
     *
     * Generated from protobuf field <code>bool is_locked = 5;</code>
     * @return bool
     */
    public function getIsLocked()
    {
        return $this->is_locked;
    }

    /**
     * Заблокирован ли спавн
     *
     * Generated from protobuf field <code>bool is_locked = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLocked($var)
    {
        GPBUtil::checkBool($var);
        $this->is_locked = $var;

        return $this;
    }

}

