<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicles/vehicles.proto

namespace Vehicles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vehicles.VehiclesListItem</code>
 */
class VehiclesListItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string model = 2;</code>
     */
    protected $model = '';
    /**
     * Generated from protobuf field <code>string numberplate = 3;</code>
     */
    protected $numberplate = '';
    /**
     * Generated from protobuf field <code>.vehicles.BodyColor primary_color = 4;</code>
     */
    protected $primary_color = null;
    /**
     * Generated from protobuf field <code>bool is_locked = 5;</code>
     */
    protected $is_locked = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $model
     *     @type string $numberplate
     *     @type \Vehicles\BodyColor $primary_color
     *     @type bool $is_locked
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vehicles\Vehicles::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string model = 2;</code>
     * @return string
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Generated from protobuf field <code>string model = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string numberplate = 3;</code>
     * @return string
     */
    public function getNumberplate()
    {
        return $this->numberplate;
    }

    /**
     * Generated from protobuf field <code>string numberplate = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNumberplate($var)
    {
        GPBUtil::checkString($var, True);
        $this->numberplate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.vehicles.BodyColor primary_color = 4;</code>
     * @return \Vehicles\BodyColor
     */
    public function getPrimaryColor()
    {
        return $this->primary_color;
    }

    /**
     * Generated from protobuf field <code>.vehicles.BodyColor primary_color = 4;</code>
     * @param \Vehicles\BodyColor $var
     * @return $this
     */
    public function setPrimaryColor($var)
    {
        GPBUtil::checkMessage($var, \Vehicles\BodyColor::class);
        $this->primary_color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_locked = 5;</code>
     * @return bool
     */
    public function getIsLocked()
    {
        return $this->is_locked;
    }

    /**
     * Generated from protobuf field <code>bool is_locked = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLocked($var)
    {
        GPBUtil::checkBool($var);
        $this->is_locked = $var;

        return $this;
    }

}

