<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth/messages.proto

namespace GPBMetadata\Auth;

class Messages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a85010a13617574682f6d657373616765732e70726f746f12046175746822260a074163636f756e74120c0a046e616d65180120012809120d0a05656d61696c18022001280942385a366769746875622e636f6d2f434344506c616e65742f636364706c616e65742d6261636b656e642f706b672f6170692f76312f61757468620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

