<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank/bank.proto

namespace Bank;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * BankAccount contains completed info of the bank account.
 *
 * Generated from protobuf message <code>bank.BankAccount</code>
 */
class BankAccount extends \Google\Protobuf\Internal\Message
{
    /**
     * ID персонажа-владельца указанного счёта в банке.
     *
     * Generated from protobuf field <code>int32 character_owner = 1;</code>
     */
    protected $character_owner = 0;
    /**
     * Список счетов персонажа.
     *
     * Generated from protobuf field <code>repeated .bank.BankAccount.CurrencyAmount bill = 2;</code>
     */
    private $bill;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $character_owner
     *           ID персонажа-владельца указанного счёта в банке.
     *     @type \Bank\BankAccount\CurrencyAmount[]|\Google\Protobuf\Internal\RepeatedField $bill
     *           Список счетов персонажа.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bank\Bank::initOnce();
        parent::__construct($data);
    }

    /**
     * ID персонажа-владельца указанного счёта в банке.
     *
     * Generated from protobuf field <code>int32 character_owner = 1;</code>
     * @return int
     */
    public function getCharacterOwner()
    {
        return $this->character_owner;
    }

    /**
     * ID персонажа-владельца указанного счёта в банке.
     *
     * Generated from protobuf field <code>int32 character_owner = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCharacterOwner($var)
    {
        GPBUtil::checkInt32($var);
        $this->character_owner = $var;

        return $this;
    }

    /**
     * Список счетов персонажа.
     *
     * Generated from protobuf field <code>repeated .bank.BankAccount.CurrencyAmount bill = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBill()
    {
        return $this->bill;
    }

    /**
     * Список счетов персонажа.
     *
     * Generated from protobuf field <code>repeated .bank.BankAccount.CurrencyAmount bill = 2;</code>
     * @param \Bank\BankAccount\CurrencyAmount[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBill($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bank\BankAccount\CurrencyAmount::class);
        $this->bill = $arr;

        return $this;
    }

}

