<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank/bank.proto

namespace Bank;

if (false) {
    /**
     * This class is deprecated. Use Bank\BankAccount\CurrencyAmount instead.
     * @deprecated
     */
    class BankAccount_CurrencyAmount {}
}
class_exists(BankAccount\CurrencyAmount::class);
@trigger_error('Bank\BankAccount_CurrencyAmount is deprecated and will be removed in the next major release. Use Bank\BankAccount\CurrencyAmount instead', E_USER_DEPRECATED);

