<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank/bank.proto

namespace Bank;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Запрос на конвертацию валют.
 *
 * Generated from protobuf message <code>bank.ConvertReq</code>
 */
class ConvertReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Валюта ИЗ которой происходит конвертация.
     *
     * Generated from protobuf field <code>.bank.Currency from = 1;</code>
     */
    protected $from = 0;
    /**
     * Валюта В которую происходит конвертация.
     *
     * Generated from protobuf field <code>.bank.Currency to = 2;</code>
     */
    protected $to = 0;
    /**
     * Сумма в валюте "from"
     *
     * Generated from protobuf field <code>int64 amount = 3;</code>
     */
    protected $amount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $from
     *           Валюта ИЗ которой происходит конвертация.
     *     @type int $to
     *           Валюта В которую происходит конвертация.
     *     @type int|string $amount
     *           Сумма в валюте "from"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bank\Bank::initOnce();
        parent::__construct($data);
    }

    /**
     * Валюта ИЗ которой происходит конвертация.
     *
     * Generated from protobuf field <code>.bank.Currency from = 1;</code>
     * @return int
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * Валюта ИЗ которой происходит конвертация.
     *
     * Generated from protobuf field <code>.bank.Currency from = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkEnum($var, \Bank\Currency::class);
        $this->from = $var;

        return $this;
    }

    /**
     * Валюта В которую происходит конвертация.
     *
     * Generated from protobuf field <code>.bank.Currency to = 2;</code>
     * @return int
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * Валюта В которую происходит конвертация.
     *
     * Generated from protobuf field <code>.bank.Currency to = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkEnum($var, \Bank\Currency::class);
        $this->to = $var;

        return $this;
    }

    /**
     * Сумма в валюте "from"
     *
     * Generated from protobuf field <code>int64 amount = 3;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Сумма в валюте "from"
     *
     * Generated from protobuf field <code>int64 amount = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

}

