<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank/bank.proto

namespace Bank;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Ответ на запрос конвертации валют.
 *
 * Generated from protobuf message <code>bank.ConvertResp</code>
 */
class ConvertResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Валюта, в которую выполнялась конвертация.
     *
     * Generated from protobuf field <code>.bank.Currency currency = 1;</code>
     */
    protected $currency = 0;
    /**
     * Результат конвертации.
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     */
    protected $amount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $currency
     *           Валюта, в которую выполнялась конвертация.
     *     @type int|string $amount
     *           Результат конвертации.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bank\Bank::initOnce();
        parent::__construct($data);
    }

    /**
     * Валюта, в которую выполнялась конвертация.
     *
     * Generated from protobuf field <code>.bank.Currency currency = 1;</code>
     * @return int
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Валюта, в которую выполнялась конвертация.
     *
     * Generated from protobuf field <code>.bank.Currency currency = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkEnum($var, \Bank\Currency::class);
        $this->currency = $var;

        return $this;
    }

    /**
     * Результат конвертации.
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Результат конвертации.
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

}

