<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank/bank.proto

namespace Bank;

if (false) {
    /**
     * This class is deprecated. Use Bank\ExchangeRates\ExchangeRate instead.
     * @deprecated
     */
    class ExchangeRates_ExchangeRate {}
}
class_exists(ExchangeRates\ExchangeRate::class);
@trigger_error('Bank\ExchangeRates_ExchangeRate is deprecated and will be removed in the next major release. Use Bank\ExchangeRates\ExchangeRate instead', E_USER_DEPRECATED);

