<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank/bank.proto

namespace Bank;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ExchangeRates информация про актуальные курсы валют в банке CCDPlanet.
 *
 * Generated from protobuf message <code>bank.ExchangeRates</code>
 */
class ExchangeRates extends \Google\Protobuf\Internal\Message
{
    /**
     * Список с курсами валют.
     *
     * Generated from protobuf field <code>repeated .bank.ExchangeRates.ExchangeRate rate = 1;</code>
     */
    private $rate;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bank\ExchangeRates\ExchangeRate[]|\Google\Protobuf\Internal\RepeatedField $rate
     *           Список с курсами валют.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bank\Bank::initOnce();
        parent::__construct($data);
    }

    /**
     * Список с курсами валют.
     *
     * Generated from protobuf field <code>repeated .bank.ExchangeRates.ExchangeRate rate = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * Список с курсами валют.
     *
     * Generated from protobuf field <code>repeated .bank.ExchangeRates.ExchangeRate rate = 1;</code>
     * @param \Bank\ExchangeRates\ExchangeRate[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRate($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bank\ExchangeRates\ExchangeRate::class);
        $this->rate = $arr;

        return $this;
    }

}

