<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank/bank.proto

namespace Bank;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Запрос на обмен валют.
 *
 * Generated from protobuf message <code>bank.ExchangeReq</code>
 */
class ExchangeReq extends \Google\Protobuf\Internal\Message
{
    /**
     * ID персонажа.
     *
     * Generated from protobuf field <code>int32 character_id = 1;</code>
     */
    protected $character_id = 0;
    /**
     * Запрос обмена.
     *
     * Generated from protobuf field <code>.bank.ConvertReq convert = 2;</code>
     */
    protected $convert = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $character_id
     *           ID персонажа.
     *     @type \Bank\ConvertReq $convert
     *           Запрос обмена.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bank\Bank::initOnce();
        parent::__construct($data);
    }

    /**
     * ID персонажа.
     *
     * Generated from protobuf field <code>int32 character_id = 1;</code>
     * @return int
     */
    public function getCharacterId()
    {
        return $this->character_id;
    }

    /**
     * ID персонажа.
     *
     * Generated from protobuf field <code>int32 character_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCharacterId($var)
    {
        GPBUtil::checkInt32($var);
        $this->character_id = $var;

        return $this;
    }

    /**
     * Запрос обмена.
     *
     * Generated from protobuf field <code>.bank.ConvertReq convert = 2;</code>
     * @return \Bank\ConvertReq
     */
    public function getConvert()
    {
        return $this->convert;
    }

    /**
     * Запрос обмена.
     *
     * Generated from protobuf field <code>.bank.ConvertReq convert = 2;</code>
     * @param \Bank\ConvertReq $var
     * @return $this
     */
    public function setConvert($var)
    {
        GPBUtil::checkMessage($var, \Bank\ConvertReq::class);
        $this->convert = $var;

        return $this;
    }

}

