<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank/bank.proto

namespace Bank;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Запись в истории
 *
 * Generated from protobuf message <code>bank.HistoryRecord</code>
 */
class HistoryRecord extends \Google\Protobuf\Internal\Message
{
    /**
     * ID записи
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Сумма
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     */
    protected $amount = 0;
    /**
     * Тип операции
     *
     * Generated from protobuf field <code>.bank.OperationType type = 3;</code>
     */
    protected $type = 0;
    /**
     * Timestamp см.
     * https://github.com/protocolbuffers/protobuf/blob/39d730dd96c81196893734ee1e075c34567e59ae/src/google/protobuf/timestamp.proto#L127
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp ts = 4;</code>
     */
    protected $ts = null;
    /**
     * Валюта
     *
     * Generated from protobuf field <code>.bank.Currency currency = 5;</code>
     */
    protected $currency = 0;
    /**
     * Описание
     *
     * Generated from protobuf field <code>string description = 6;</code>
     */
    protected $description = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           ID записи
     *     @type int|string $amount
     *           Сумма
     *     @type int $type
     *           Тип операции
     *     @type \Google\Protobuf\Timestamp $ts
     *           Timestamp см.
     *           https://github.com/protocolbuffers/protobuf/blob/39d730dd96c81196893734ee1e075c34567e59ae/src/google/protobuf/timestamp.proto#L127
     *     @type int $currency
     *           Валюта
     *     @type string $description
     *           Описание
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bank\Bank::initOnce();
        parent::__construct($data);
    }

    /**
     * ID записи
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * ID записи
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Сумма
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Сумма
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Тип операции
     *
     * Generated from protobuf field <code>.bank.OperationType type = 3;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Тип операции
     *
     * Generated from protobuf field <code>.bank.OperationType type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Bank\OperationType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Timestamp см.
     * https://github.com/protocolbuffers/protobuf/blob/39d730dd96c81196893734ee1e075c34567e59ae/src/google/protobuf/timestamp.proto#L127
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp ts = 4;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getTs()
    {
        return $this->ts;
    }

    /**
     * Timestamp см.
     * https://github.com/protocolbuffers/protobuf/blob/39d730dd96c81196893734ee1e075c34567e59ae/src/google/protobuf/timestamp.proto#L127
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp ts = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTs($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->ts = $var;

        return $this;
    }

    /**
     * Валюта
     *
     * Generated from protobuf field <code>.bank.Currency currency = 5;</code>
     * @return int
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Валюта
     *
     * Generated from protobuf field <code>.bank.Currency currency = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkEnum($var, \Bank\Currency::class);
        $this->currency = $var;

        return $this;
    }

    /**
     * Описание
     *
     * Generated from protobuf field <code>string description = 6;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Описание
     *
     * Generated from protobuf field <code>string description = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

}

