<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank/bank.proto

namespace Bank;

if (false) {
    /**
     * This class is deprecated. Use Bank\Summary\StatInfo instead.
     * @deprecated
     */
    class Summary_StatInfo {}
}
class_exists(Summary\StatInfo::class);
@trigger_error('Bank\Summary_StatInfo is deprecated and will be removed in the next major release. Use Bank\Summary\StatInfo instead', E_USER_DEPRECATED);

