<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: accounts/accounts.proto

namespace Accounts;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Идентификатор аккаунта по имени.
 *
 * Generated from protobuf message <code>accounts.FindAccountByNameReq</code>
 */
class FindAccountByNameReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Имя аккаунта.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Имя аккаунта.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Accounts\Accounts::initOnce();
        parent::__construct($data);
    }

    /**
     * Имя аккаунта.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Имя аккаунта.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

