<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: accounts/accounts.proto

namespace Accounts;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Идентификатор аккаунта по ID.
 *
 * Generated from protobuf message <code>accounts.FindAccountByIDReq</code>
 */
class FindAccountByIDReq extends \Google\Protobuf\Internal\Message
{
    /**
     * ID аккаунта.
     *
     * Generated from protobuf field <code>int32 id = 2;</code>
     */
    protected $id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *           ID аккаунта.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Accounts\Accounts::initOnce();
        parent::__construct($data);
    }

    /**
     * ID аккаунта.
     *
     * Generated from protobuf field <code>int32 id = 2;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * ID аккаунта.
     *
     * Generated from protobuf field <code>int32 id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

}

