<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank/bank.proto

namespace Bank\Summary;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bank.Summary.StatInfo</code>
 */
class StatInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Валюта
     *
     * Generated from protobuf field <code>.bank.Currency currency = 1;</code>
     */
    protected $currency = 0;
    /**
     * Сумма
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     */
    protected $amount = 0;
    /**
     * Тип операции
     *
     * Generated from protobuf field <code>.bank.OperationType type = 3;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $currency
     *           Валюта
     *     @type int|string $amount
     *           Сумма
     *     @type int $type
     *           Тип операции
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bank\Bank::initOnce();
        parent::__construct($data);
    }

    /**
     * Валюта
     *
     * Generated from protobuf field <code>.bank.Currency currency = 1;</code>
     * @return int
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Валюта
     *
     * Generated from protobuf field <code>.bank.Currency currency = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkEnum($var, \Bank\Currency::class);
        $this->currency = $var;

        return $this;
    }

    /**
     * Сумма
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Сумма
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Тип операции
     *
     * Generated from protobuf field <code>.bank.OperationType type = 3;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Тип операции
     *
     * Generated from protobuf field <code>.bank.OperationType type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Bank\OperationType::class);
        $this->type = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StatInfo::class, \Bank\Summary_StatInfo::class);

