<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory/inventory.proto

namespace Inventory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Boost представляет эффект, который может быть наложен на предмет.
 *
 * Generated from protobuf message <code>inventory.Boost</code>
 */
class Boost extends \Google\Protobuf\Internal\Message
{
    /**
     * Имя эффекта.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Описание эффекта.
     *
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * Уровень эффекта.
     *
     * Generated from protobuf field <code>int32 level = 3;</code>
     */
    protected $level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Имя эффекта.
     *     @type string $description
     *           Описание эффекта.
     *     @type int $level
     *           Уровень эффекта.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inventory\Inventory::initOnce();
        parent::__construct($data);
    }

    /**
     * Имя эффекта.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Имя эффекта.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Описание эффекта.
     *
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Описание эффекта.
     *
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Уровень эффекта.
     *
     * Generated from protobuf field <code>int32 level = 3;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Уровень эффекта.
     *
     * Generated from protobuf field <code>int32 level = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->level = $var;

        return $this;
    }

}

