<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory/inventory.proto

namespace Inventory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Item представляет предмет в инвентаре.
 *
 * Generated from protobuf message <code>inventory.Item</code>
 */
class Item extends \Google\Protobuf\Internal\Message
{
    /**
     * id предмета.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * name имя предмета.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * stack_size максимальный размер стака.
     *
     * Generated from protobuf field <code>int32 stack_size = 3;</code>
     */
    protected $stack_size = 0;
    /**
     * boosts список бустов (эффектов) на предмете.
     *
     * Generated from protobuf field <code>repeated .inventory.Boost boosts = 4;</code>
     */
    private $boosts;
    /**
     * special_slot специальный слот, в который может надеваться носимый предмет.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value special_slot = 5;</code>
     */
    protected $special_slot = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           id предмета.
     *     @type string $name
     *           name имя предмета.
     *     @type int $stack_size
     *           stack_size максимальный размер стака.
     *     @type \Inventory\Boost[]|\Google\Protobuf\Internal\RepeatedField $boosts
     *           boosts список бустов (эффектов) на предмете.
     *     @type \Google\Protobuf\Int32Value $special_slot
     *           special_slot специальный слот, в который может надеваться носимый предмет.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inventory\Inventory::initOnce();
        parent::__construct($data);
    }

    /**
     * id предмета.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * id предмета.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * name имя предмета.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * name имя предмета.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * stack_size максимальный размер стака.
     *
     * Generated from protobuf field <code>int32 stack_size = 3;</code>
     * @return int
     */
    public function getStackSize()
    {
        return $this->stack_size;
    }

    /**
     * stack_size максимальный размер стака.
     *
     * Generated from protobuf field <code>int32 stack_size = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStackSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->stack_size = $var;

        return $this;
    }

    /**
     * boosts список бустов (эффектов) на предмете.
     *
     * Generated from protobuf field <code>repeated .inventory.Boost boosts = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBoosts()
    {
        return $this->boosts;
    }

    /**
     * boosts список бустов (эффектов) на предмете.
     *
     * Generated from protobuf field <code>repeated .inventory.Boost boosts = 4;</code>
     * @param \Inventory\Boost[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBoosts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inventory\Boost::class);
        $this->boosts = $arr;

        return $this;
    }

    /**
     * special_slot специальный слот, в который может надеваться носимый предмет.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value special_slot = 5;</code>
     * @return \Google\Protobuf\Int32Value
     */
    public function getSpecialSlot()
    {
        return $this->special_slot;
    }

    /**
     * Returns the unboxed value from <code>getSpecialSlot()</code>

     * special_slot специальный слот, в который может надеваться носимый предмет.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value special_slot = 5;</code>
     * @return int|null
     */
    public function getSpecialSlotUnwrapped()
    {
        return $this->readWrapperValue("special_slot");
    }

    /**
     * special_slot специальный слот, в который может надеваться носимый предмет.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value special_slot = 5;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setSpecialSlot($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
        $this->special_slot = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int32Value object.

     * special_slot специальный слот, в который может надеваться носимый предмет.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value special_slot = 5;</code>
     * @param int|null $var
     * @return $this
     */
    public function setSpecialSlotUnwrapped($var)
    {
        $this->writeWrapperValue("special_slot", $var);
        return $this;}

}

