<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory/inventory.proto

namespace Inventory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Move сообщение для перемещения предмета между слотами.
 *
 * Generated from protobuf message <code>inventory.Move</code>
 */
class Move extends \Google\Protobuf\Internal\Message
{
    /**
     * from слот откуда переместить предмет.
     *
     * Generated from protobuf field <code>int32 from = 1;</code>
     */
    protected $from = 0;
    /**
     * to слот куда переместить предмет.
     *
     * Generated from protobuf field <code>int32 to = 2;</code>
     */
    protected $to = 0;
    /**
     * amount количество перемещаемых предметов.
     *
     * Generated from protobuf field <code>int32 amount = 3;</code>
     */
    protected $amount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $from
     *           from слот откуда переместить предмет.
     *     @type int $to
     *           to слот куда переместить предмет.
     *     @type int $amount
     *           amount количество перемещаемых предметов.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inventory\Inventory::initOnce();
        parent::__construct($data);
    }

    /**
     * from слот откуда переместить предмет.
     *
     * Generated from protobuf field <code>int32 from = 1;</code>
     * @return int
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * from слот откуда переместить предмет.
     *
     * Generated from protobuf field <code>int32 from = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkInt32($var);
        $this->from = $var;

        return $this;
    }

    /**
     * to слот куда переместить предмет.
     *
     * Generated from protobuf field <code>int32 to = 2;</code>
     * @return int
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * to слот куда переместить предмет.
     *
     * Generated from protobuf field <code>int32 to = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkInt32($var);
        $this->to = $var;

        return $this;
    }

    /**
     * amount количество перемещаемых предметов.
     *
     * Generated from protobuf field <code>int32 amount = 3;</code>
     * @return int
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * amount количество перемещаемых предметов.
     *
     * Generated from protobuf field <code>int32 amount = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt32($var);
        $this->amount = $var;

        return $this;
    }

}

