<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory/inventory.proto

namespace Inventory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Moved результат перемещения между слотами.
 *
 * Generated from protobuf message <code>inventory.Moved</code>
 */
class Moved extends \Google\Protobuf\Internal\Message
{
    /**
     * from обновлённый слот откуда было выполнено перемещение.
     *
     * Generated from protobuf field <code>.inventory.Slot from = 1;</code>
     */
    protected $from = null;
    /**
     * to обновлённый слот куда было выполнено перемещение.
     *
     * Generated from protobuf field <code>.inventory.Slot to = 2;</code>
     */
    protected $to = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Inventory\Slot $from
     *           from обновлённый слот откуда было выполнено перемещение.
     *     @type \Inventory\Slot $to
     *           to обновлённый слот куда было выполнено перемещение.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inventory\Inventory::initOnce();
        parent::__construct($data);
    }

    /**
     * from обновлённый слот откуда было выполнено перемещение.
     *
     * Generated from protobuf field <code>.inventory.Slot from = 1;</code>
     * @return \Inventory\Slot
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * from обновлённый слот откуда было выполнено перемещение.
     *
     * Generated from protobuf field <code>.inventory.Slot from = 1;</code>
     * @param \Inventory\Slot $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkMessage($var, \Inventory\Slot::class);
        $this->from = $var;

        return $this;
    }

    /**
     * to обновлённый слот куда было выполнено перемещение.
     *
     * Generated from protobuf field <code>.inventory.Slot to = 2;</code>
     * @return \Inventory\Slot
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * to обновлённый слот куда было выполнено перемещение.
     *
     * Generated from protobuf field <code>.inventory.Slot to = 2;</code>
     * @param \Inventory\Slot $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkMessage($var, \Inventory\Slot::class);
        $this->to = $var;

        return $this;
    }

}

