<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: houses/houses.proto

namespace Houses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Фильтры работают с массивами данных
 *
 * Generated from protobuf message <code>houses.ApartmentFilters</code>
 */
class ApartmentFilters extends \Google\Protobuf\Internal\Message
{
    /**
     * Владелец квартир
     *
     * Generated from protobuf field <code>int32 owner_id = 1;</code>
     */
    protected $owner_id = 0;
    /**
     * ID квартир.
     *
     * Generated from protobuf field <code>repeated int32 ids = 2;</code>
     */
    private $ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $owner_id
     *           Владелец квартир
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $ids
     *           ID квартир.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Houses\Houses::initOnce();
        parent::__construct($data);
    }

    /**
     * Владелец квартир
     *
     * Generated from protobuf field <code>int32 owner_id = 1;</code>
     * @return int
     */
    public function getOwnerId()
    {
        return $this->owner_id;
    }

    /**
     * Владелец квартир
     *
     * Generated from protobuf field <code>int32 owner_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * ID квартир.
     *
     * Generated from protobuf field <code>repeated int32 ids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIds()
    {
        return $this->ids;
    }

    /**
     * ID квартир.
     *
     * Generated from protobuf field <code>repeated int32 ids = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->ids = $arr;

        return $this;
    }

}

