<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: houses/houses.proto

namespace Houses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Идентификатор квартиры.
 *
 * Generated from protobuf message <code>houses.ApartmentIdentifier</code>
 */
class ApartmentIdentifier extends \Google\Protobuf\Internal\Message
{
    protected $identifier;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Houses\ApartmentIdentifier\WithID $with_id
     *           Идентификатор по ID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Houses\Houses::initOnce();
        parent::__construct($data);
    }

    /**
     * Идентификатор по ID
     *
     * Generated from protobuf field <code>.houses.ApartmentIdentifier.WithID with_id = 1;</code>
     * @return \Houses\ApartmentIdentifier\WithID
     */
    public function getWithId()
    {
        return $this->readOneof(1);
    }

    /**
     * Идентификатор по ID
     *
     * Generated from protobuf field <code>.houses.ApartmentIdentifier.WithID with_id = 1;</code>
     * @param \Houses\ApartmentIdentifier\WithID $var
     * @return $this
     */
    public function setWithId($var)
    {
        GPBUtil::checkMessage($var, \Houses\ApartmentIdentifier_WithID::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getIdentifier()
    {
        return $this->whichOneof("identifier");
    }

}

