<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: houses/houses.proto

namespace Houses;

if (false) {
    /**
     * This class is deprecated. Use Houses\ApartmentIdentifier\WithID instead.
     * @deprecated
     */
    class ApartmentIdentifier_WithID {}
}
class_exists(ApartmentIdentifier\WithID::class);
@trigger_error('Houses\ApartmentIdentifier_WithID is deprecated and will be removed in the next major release. Use Houses\ApartmentIdentifier\WithID instead', E_USER_DEPRECATED);

