<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: houses/houses.proto

namespace Houses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>houses.BuyReq</code>
 */
class BuyReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.houses.ApartmentIdentifier identifier = 1;</code>
     */
    protected $identifier = null;
    /**
     * Generated from protobuf field <code>int32 character_id = 2;</code>
     */
    protected $character_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Houses\ApartmentIdentifier $identifier
     *     @type int $character_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Houses\Houses::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.houses.ApartmentIdentifier identifier = 1;</code>
     * @return \Houses\ApartmentIdentifier
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * Generated from protobuf field <code>.houses.ApartmentIdentifier identifier = 1;</code>
     * @param \Houses\ApartmentIdentifier $var
     * @return $this
     */
    public function setIdentifier($var)
    {
        GPBUtil::checkMessage($var, \Houses\ApartmentIdentifier::class);
        $this->identifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 character_id = 2;</code>
     * @return int
     */
    public function getCharacterId()
    {
        return $this->character_id;
    }

    /**
     * Generated from protobuf field <code>int32 character_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCharacterId($var)
    {
        GPBUtil::checkInt32($var);
        $this->character_id = $var;

        return $this;
    }

}

