<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank/bank.proto

namespace Bank\BankAccount;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bank.BankAccount.CurrencyAmount</code>
 */
class CurrencyAmount extends \Google\Protobuf\Internal\Message
{
    /**
     * Currency валюта, в которой открыт счёт.
     *
     * Generated from protobuf field <code>.bank.Currency currency = 1;</code>
     */
    protected $currency = 0;
    /**
     * Сумма на счёте в валюте currency
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     */
    protected $amount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $currency
     *           Currency валюта, в которой открыт счёт.
     *     @type int|string $amount
     *           Сумма на счёте в валюте currency
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bank\Bank::initOnce();
        parent::__construct($data);
    }

    /**
     * Currency валюта, в которой открыт счёт.
     *
     * Generated from protobuf field <code>.bank.Currency currency = 1;</code>
     * @return int
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Currency валюта, в которой открыт счёт.
     *
     * Generated from protobuf field <code>.bank.Currency currency = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkEnum($var, \Bank\Currency::class);
        $this->currency = $var;

        return $this;
    }

    /**
     * Сумма на счёте в валюте currency
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Сумма на счёте в валюте currency
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CurrencyAmount::class, \Bank\BankAccount_CurrencyAmount::class);

