<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: garages/garages.proto

namespace Garages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Гараж
 *
 * Generated from protobuf message <code>garages.Garage</code>
 */
class Garage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.garages.GarageRoom room = 2;</code>
     */
    protected $room = 0;
    /**
     * ID квартиры
     *
     * Generated from protobuf field <code>int32 apartment_id = 7;</code>
     */
    protected $apartment_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $room
     *     @type int $apartment_id
     *           ID квартиры
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Garages\Garages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.garages.GarageRoom room = 2;</code>
     * @return int
     */
    public function getRoom()
    {
        return $this->room;
    }

    /**
     * Generated from protobuf field <code>.garages.GarageRoom room = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRoom($var)
    {
        GPBUtil::checkEnum($var, \Garages\GarageRoom::class);
        $this->room = $var;

        return $this;
    }

    /**
     * ID квартиры
     *
     * Generated from protobuf field <code>int32 apartment_id = 7;</code>
     * @return int
     */
    public function getApartmentId()
    {
        return $this->apartment_id;
    }

    /**
     * ID квартиры
     *
     * Generated from protobuf field <code>int32 apartment_id = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setApartmentId($var)
    {
        GPBUtil::checkInt32($var);
        $this->apartment_id = $var;

        return $this;
    }

}

