<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: garages/garages.proto

namespace Garages;

if (false) {
    /**
     * This class is deprecated. Use Garages\GarageIdentifier\WithID instead.
     * @deprecated
     */
    class GarageIdentifier_WithID {}
}
class_exists(GarageIdentifier\WithID::class);
@trigger_error('Garages\GarageIdentifier_WithID is deprecated and will be removed in the next major release. Use Garages\GarageIdentifier\WithID instead', E_USER_DEPRECATED);

