<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: garages/garages.proto

namespace Garages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Фильтры для работы с массивами данных.
 *
 * Generated from protobuf message <code>garages.GarageFilters</code>
 */
class GarageFilters extends \Google\Protobuf\Internal\Message
{
    /**
     * ID персонажа, который владеец гаражом.
     *
     * Generated from protobuf field <code>int32 owner_id = 1;</code>
     */
    protected $owner_id = 0;
    /**
     * ID квартиры, к которой принадлежит гараж.
     *
     * Generated from protobuf field <code>int32 apartment_id = 2;</code>
     */
    protected $apartment_id = 0;
    /**
     * Список ID гаражей.
     *
     * Generated from protobuf field <code>repeated int32 garage_ids = 3;</code>
     */
    private $garage_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $owner_id
     *           ID персонажа, который владеец гаражом.
     *     @type int $apartment_id
     *           ID квартиры, к которой принадлежит гараж.
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $garage_ids
     *           Список ID гаражей.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Garages\Garages::initOnce();
        parent::__construct($data);
    }

    /**
     * ID персонажа, который владеец гаражом.
     *
     * Generated from protobuf field <code>int32 owner_id = 1;</code>
     * @return int
     */
    public function getOwnerId()
    {
        return $this->owner_id;
    }

    /**
     * ID персонажа, который владеец гаражом.
     *
     * Generated from protobuf field <code>int32 owner_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * ID квартиры, к которой принадлежит гараж.
     *
     * Generated from protobuf field <code>int32 apartment_id = 2;</code>
     * @return int
     */
    public function getApartmentId()
    {
        return $this->apartment_id;
    }

    /**
     * ID квартиры, к которой принадлежит гараж.
     *
     * Generated from protobuf field <code>int32 apartment_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setApartmentId($var)
    {
        GPBUtil::checkInt32($var);
        $this->apartment_id = $var;

        return $this;
    }

    /**
     * Список ID гаражей.
     *
     * Generated from protobuf field <code>repeated int32 garage_ids = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGarageIds()
    {
        return $this->garage_ids;
    }

    /**
     * Список ID гаражей.
     *
     * Generated from protobuf field <code>repeated int32 garage_ids = 3;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGarageIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->garage_ids = $arr;

        return $this;
    }

}

